const express = require("express");
const PptxGenJS = require("pptxgenjs");
const path = require("path");
const fs = require("fs");

const router = express.Router();

router.post("/", async (req, res) => {
  try {
    const { title, slides } = req.body;
    if (!slides || !Array.isArray(slides)) {
      return res.status(400).json({ error: "Invalid slides data" });
    }

    const pptx = new PptxGenJS();

    // ✅ Optional cover slide
    if (title) {
      const cover = pptx.addSlide();
      cover.background = { color: "F5F7FA" };
      cover.addText(title, {
        x: 0.5,
        y: 2.5,
        w: 9,
        align: "center",
        fontSize: 40,
        bold: true,
        color: "003366",
      });
    }

    slides.forEach((slideData, index) => {
      const slide = pptx.addSlide();
      slide.background = { color: "FFFFFF" };

      // 🏷️ Slide Title
      slide.addText(slideData.title || `Slide ${index + 1}`, {
        x: 0.5,
        y: 0.5,
        w: 9,
        align: "center",
        fontSize: 26,
        bold: true,
        color: "003366",
      });

      // 📐 Layout control
      let yPos = 1.4;
      const xPos = 0.7;
      const maxWidth = 8.5;
      const sectionGap = 0.2;

      if (slideData.content && Array.isArray(slideData.content)) {
        slideData.content.forEach((block) => {
          if (block.type === "heading") {
            slide.addText(block.text || "", {
              x: xPos,
              y: yPos,
              w: maxWidth,
              fontSize: 20,
              bold: true,
              color: "0055A5",
            });
            yPos += 0.5;
          }

          else if (block.type === "paragraph") {
            // 🧠 Balanced paragraph block
            slide.addText(block.text || "", {
              x: xPos,
              y: yPos,
              w: maxWidth,
              h: 1.4,
              fontSize: 16,
              color: "333333",
              lineSpacing: 22,
              valign: "top",
              wrap: true,
              autoFit: true,
            });
            yPos += 1.5; // ✅ reduced from 2.0 to fix big gaps
          }

          else if (block.type === "list" && Array.isArray(block.items)) {
            // ✅ Convert to bullet object array (avoids string bug)
            const listItems = block.items.map((item) => ({ text: item }));
            const listHeight = Math.min(3, listItems.length * 0.35 + 0.3);

            slide.addText(listItems, {
              x: xPos + 0.2,
              y: yPos + 0.2, // ✅ reduced spacing for smooth flow
              w: maxWidth - 1,
              h: listHeight,
              fontSize: 16,
              color: "111111",
              lineSpacing: 20,
              bullet: true,
              wrap: true,
            });
            yPos += listHeight + sectionGap;
          }
        });
      }

      // 🧾 Footer
      slide.addText("Generated by AI Slide Generator", {
        x: 0.5,
        y: 6.8,
        w: 9,
        fontSize: 10,
        color: "777777",
        align: "center",
      });
    });

    // 💾 Save PPT
    const outputDir = path.join(__dirname, "../public");
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);
    const fileName = `slides_${Date.now()}.pptx`;
    const filePath = path.join(outputDir, fileName);

    await pptx.writeFile({ fileName: filePath });
    res.json({ downloadUrl: `https://playground-app-9o3y.onrender.com/${fileName}` });
  } catch (err) {
    console.error("PPT generation error:", err);
    res.status(500).json({ error: "PPT generation failed", details: err.message });
  }
});

module.exports = router;
